version: "3.1"

services:

  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "3333:5432"
  xyz_pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8000:80
